steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-eu02
    integrationFlowId: I565942-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-eu02
    integrationFlowId: I565942-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-eu02
    integrationFlowId: I565942-flow4
    integrationFlowName: I565942-flow4
    packageId: CICD
    filePath: I565942-flow4.zip